python cross_metric.py --src_lan en --tgt_lan zh --forward it --backward it --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan zh --tgt_lan en --forward it --backward it --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan de --forward it --backward it --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan de --tgt_lan en --forward it --backward it --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan ru --forward it --backward it --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan ru --tgt_lan en --forward it --backward it --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan he --forward it --backward it --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan he --tgt_lan en --forward it --backward it --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan zh --forward tear --backward tear --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan zh --tgt_lan en --forward tear --backward tear --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan de --forward tear --backward tear --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan de --tgt_lan en --forward tear --backward tear --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan ru --forward tear --backward tear --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan ru --tgt_lan en --forward tear --backward tear --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan he --forward tear --backward tear --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan he --tgt_lan en --forward tear --backward tear --metric r --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan zh --forward it --backward it --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan zh --tgt_lan en --forward it --backward it --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan de --forward it --backward it --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan de --tgt_lan en --forward it --backward it --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan ru --forward it --backward it --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan ru --tgt_lan en --forward it --backward it --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan he --forward it --backward it --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan he --tgt_lan en --forward it --backward it --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan zh --forward tear --backward tear --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan zh --tgt_lan en --forward tear --backward tear --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan de --forward tear --backward tear --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan de --tgt_lan en --forward tear --backward tear --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan ru --forward tear --backward tear --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan ru --tgt_lan en --forward tear --backward tear --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan he --forward tear --backward tear --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan he --tgt_lan en --forward tear --backward tear --metric p --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan zh --forward it --backward it --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan zh --tgt_lan en --forward it --backward it --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan de --forward it --backward it --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan de --tgt_lan en --forward it --backward it --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan ru --forward it --backward it --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan ru --tgt_lan en --forward it --backward it --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan he --forward it --backward it --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan he --tgt_lan en --forward it --backward it --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan zh --forward tear --backward tear --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan zh --tgt_lan en --forward tear --backward tear --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan de --forward tear --backward tear --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan de --tgt_lan en --forward tear --backward tear --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan ru --forward tear --backward tear --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan ru --tgt_lan en --forward tear --backward tear --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan en --tgt_lan he --forward tear --backward tear --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro
python cross_metric.py --src_lan he --tgt_lan en --forward tear --backward tear --metric f --t_metric bleurt --models gpt-3.5-turbo gpt-4o claude-3-opus claude-3.5-sonnet gemini-pro